os:
  - linux
dist: trusty
sudo: required
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
python:
  - "2.7"
before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
    -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --get channels
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda config --add channels https://conda.anaconda.org/thoba
  - conda info -a
  - conda install kraken2
install:
  - conda install pip conda-build anaconda-client
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest -v test/
after_success:
  - test $TRAVIS_BRANCH = "master" && bash conda/conda_upload.sh
