{% set version = "0.1.3" %}
{% set sha256 = "8ae72d4c136edff4e755462f6c57c903edb8479ea68d6f0ccdb38f6c56e42d04" %}

package:
  name: confil
  version: {{ version }}

source:
  url: https://github.com/COMBAT-TB/confil/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 1

requirements:
  build:
    - python
    - click
  run:
    - python
    - click
    - kraken2

test:
  commands:
    - confil |& grep confil
  imports:
    - confil

about:
  home: https://github.com/COMBAT-TB/confil
  license_file: LICENSE
  summary: "confil parses a kraken2 report and determines contamination based on a specified cutoff."
  dev_url: https://github.com/COMBAT-TB/confil
