{% set version = "0.1.5" %}
{% set sha256 = "9e92cf4ebbbad9c0571cbcfc014e824cd74a135e5449085205269c3b6f40209b" %}

package:
  name: confil
  version: {{ version }}

source:
  url: https://github.com/COMBAT-TB/confil/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  build:
    - python
    - click
  run:
    - python
    - click
    - kraken2

test:
  commands:
    - confil |& grep confil
  imports:
    - confil

about:
  home: https://github.com/COMBAT-TB/confil
  license_file: LICENSE
  summary: "confil parses a kraken2 report and determines contamination based on a specified cutoff."
  dev_url: https://github.com/COMBAT-TB/confil
